services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Shapecode\Bundle\Doctrine\SessionHandlerBundle\Command\ClearSessionCommand: ~
    Shapecode\Bundle\Doctrine\SessionHandlerBundle\Session\Handler\DoctrineHandler: ~
